version: "3.9"

services:
  library_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    container_name: library_app

  mysql_db_server_mlm:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "MLM_DB"
      MYSQL_ROOT_PASSWORD: "sql1234"
      MYSQL_USER: 'sara'
      MYSQL_PASSWORD: 'a1234'

    volumes:
      - ./src/database/createDB.sql:/docker-entrypoint-initdb.d/run_createDB.sql
    container_name: mysql_db_server_mlm
