version: "3.9"

services:
  library_app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    networks:
        - network
    ports:
      - "8084:8084"
    depends_on:
      - mysql_db_server_mlm
    container_name: library_app

  mysql_db_server_mlm:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - network
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "MLM_DB"
      MYSQL_ROOT_PASSWORD: "sql1234"
    volumes:
      - ./src/database/scripts/createDB.sql:/docker-entrypoint-initdb.d/run_createDB.sql
    container_name: mysql_db_server_mlm

networks:
  network:
    name: mlm_network
